_BASE_: "Base-Panoptic.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [ False, True, True, True ]
    DEFORM_MODULATED: True
    DEFORM_INTERVAL: 3
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/panoptic/CondInst/R_101_dcni3_3x"
