_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "./pretrain/R-50.pkl"
  RESNETS:
    DEPTH: 50
INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/fcos/R_50_3x"

SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000  # 3x

# DATALOADER:
#   NUM_WORKERS: 2

TEST:
  EVAL_PERIOD: 5000