_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "" #"./pretrain/coco_pretrain.pth"
  RESNETS:
    DEPTH: 50
    NORM: "GN"
  BACKBONE:
    FREEZE_AT: 0

INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/fcos/R_50_1x"



SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000  # 3x

DATALOADER:
  NUM_WORKERS: 2

TEST:
  EVAL_PERIOD: 2000