_BASE_: "Base-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  CONDINST:
    MASK_HEAD:
      NUM_LAYERS: 1 #(AKA:'depth', default = 3)
      CHANNELS: 8  #(AKA:'width', default = 8)
OUTPUT_DIR: "output/condinst_MS_R_50_1x"
